[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
token_faucet = "Ceu7xwhh4URJ9pFEyLSWhaQWXpbk92PhUzWsw1C8GsKZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ken/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
